version: "3.8"

services:
  database_login:
    image: postgres
    container_name: database_login
    restart: always
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=login
      - POSTGRES_DB=login
    volumes: 
      - pgdata:/data/postgres
    network_mode: host
  app:
    build: .
    container_name: login_page
    volumes:
      - .:/usr/app
    network_mode: host

volumes:
  pgdata:
    driver: local